// Generated by build/build_inventory.py from the April 2025 utilization report.
window.MERCY_INVENTORY = {
  "building": "Main Hall",
  "buildingCode": "MH",
  "address": "555 Broadway, Dobbs Ferry, NY 10522",
  "source": "Mercy University Instructional Space Needs Analysis, April 2025",
  "scopeNote": "Instructional inventory only; non-instructional rooms are not included.",
  "departmentNote": "Departments are scheduled course users in the Fall 2023 daytime appendix, not verified permanent room ownership.",
  "rooms": [
    {
      "room": "MH111",
      "floor": "1",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 724,
      "seats": 36,
      "asfPerSeat": 20.1,
      "courseCount": 11,
      "seatOccupancy": 55,
      "weeklyHours": 29.7,
      "hoursPercent": 80,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Business",
        "School of Social & Behavioral Sciences",
        "School of Health & Natural Sciences",
        "School of Nursing"
      ],
      "departmentUse": {
        "School of Business": 3,
        "School of Health & Natural Sciences": 1,
        "School of Social & Behavioral Sciences": 2,
        "School of Liberal Arts": 4,
        "School of Nursing": 1
      }
    },
    {
      "room": "MH113",
      "floor": "1",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 1558,
      "seats": 36,
      "asfPerSeat": 43.3,
      "courseCount": 12,
      "seatOccupancy": 50,
      "weeklyHours": 32.8,
      "hoursPercent": 88,
      "comment": "",
      "departments": [
        "School of Social & Behavioral Sciences",
        "School of Liberal Arts",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 4,
        "School of Health & Natural Sciences": 2,
        "School of Social & Behavioral Sciences": 6
      }
    },
    {
      "room": "MH200",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 277,
      "seats": 15,
      "asfPerSeat": 18.5,
      "courseCount": 3,
      "seatOccupancy": 73,
      "weeklyHours": 7.1,
      "hoursPercent": 19,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 2,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH201",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 359,
      "seats": 20,
      "asfPerSeat": 18.0,
      "courseCount": 12,
      "seatOccupancy": 83,
      "weeklyHours": 32.4,
      "hoursPercent": 87,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Business",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 10,
        "School of Business": 1,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH202",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 368,
      "seats": 24,
      "asfPerSeat": 15.3,
      "courseCount": 12,
      "seatOccupancy": 81,
      "weeklyHours": 36.2,
      "hoursPercent": 97,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 7,
        "School of Social & Behavioral Sciences": 4,
        "School of Health & Natural Sciences": 1
      }
    },
    {
      "room": "MH203",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 370,
      "seats": 20,
      "asfPerSeat": 18.5,
      "courseCount": 11,
      "seatOccupancy": 76,
      "weeklyHours": 29.4,
      "hoursPercent": 79,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 9,
        "School of Social & Behavioral Sciences": 2
      }
    },
    {
      "room": "MH204",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 357,
      "seats": 20,
      "asfPerSeat": 17.9,
      "courseCount": 12,
      "seatOccupancy": 80,
      "weeklyHours": 33.3,
      "hoursPercent": 89,
      "comment": "",
      "departments": [
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Liberal Arts": 12
      }
    },
    {
      "room": "MH205",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 608,
      "seats": 30,
      "asfPerSeat": 20.3,
      "courseCount": 12,
      "seatOccupancy": 77,
      "weeklyHours": 31.3,
      "hoursPercent": 84,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences",
        "School of Business"
      ],
      "departmentUse": {
        "School of Liberal Arts": 3,
        "School of Health & Natural Sciences": 4,
        "School of Social & Behavioral Sciences": 3,
        "School of Business": 2
      }
    },
    {
      "room": "MH206",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 341,
      "seats": 18,
      "asfPerSeat": 18.9,
      "courseCount": 6,
      "seatOccupancy": 56,
      "weeklyHours": 13.8,
      "hoursPercent": 37,
      "comment": "",
      "departments": [
        "School of Social & Behavioral Sciences",
        "School of Health & Natural Sciences",
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 2,
        "School of Liberal Arts": 1,
        "School of Social & Behavioral Sciences": 3
      }
    },
    {
      "room": "MH211",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 910,
      "seats": 42,
      "asfPerSeat": 21.7,
      "courseCount": 14,
      "seatOccupancy": 55,
      "weeklyHours": 35.8,
      "hoursPercent": 96,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Nursing",
        "School of Liberal Arts",
        "School of Business",
        "School of Education"
      ],
      "departmentUse": {
        "School of Liberal Arts": 2,
        "School of Health & Natural Sciences": 7,
        "School of Business": 1,
        "School of Education": 1,
        "School of Nursing": 3
      }
    },
    {
      "room": "MH213",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 950,
      "seats": 30,
      "asfPerSeat": 31.7,
      "courseCount": 12,
      "seatOccupancy": 60,
      "weeklyHours": 32.7,
      "hoursPercent": 88,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences",
        "School of Business",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Social & Behavioral Sciences": 4,
        "School of Liberal Arts": 6,
        "School of Business": 1,
        "School of Health & Natural Sciences": 1
      }
    },
    {
      "room": "MH219",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 309,
      "seats": 18,
      "asfPerSeat": 17.2,
      "courseCount": 8,
      "seatOccupancy": 88,
      "weeklyHours": 22.7,
      "hoursPercent": 61,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 7,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH236",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 363,
      "seats": 18,
      "asfPerSeat": 20.2,
      "courseCount": 6,
      "seatOccupancy": 83,
      "weeklyHours": 17.0,
      "hoursPercent": 46,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Business"
      ],
      "departmentUse": {
        "School of Liberal Arts": 5,
        "School of Business": 1
      }
    },
    {
      "room": "MH238",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 564,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 10,
      "seatOccupancy": 58,
      "weeklyHours": 30.2,
      "hoursPercent": 81,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 5,
        "School of Liberal Arts": 4,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH240",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 564,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 10,
      "seatOccupancy": 63,
      "weeklyHours": 29.3,
      "hoursPercent": 79,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Health & Natural Sciences",
        "School of Nursing",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 3,
        "School of Liberal Arts": 5,
        "School of Nursing": 1,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH241",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 563,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 13,
      "seatOccupancy": 68,
      "weeklyHours": 35.0,
      "hoursPercent": 94,
      "comment": "",
      "departments": [
        "School of Social & Behavioral Sciences",
        "School of Liberal Arts",
        "School of Nursing"
      ],
      "departmentUse": {
        "School of Liberal Arts": 5,
        "School of Social & Behavioral Sciences": 7,
        "School of Nursing": 1
      }
    },
    {
      "room": "MH242",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 610,
      "seats": 35,
      "asfPerSeat": 17.4,
      "courseCount": 10,
      "seatOccupancy": 63,
      "weeklyHours": 24.7,
      "hoursPercent": 66,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Business",
        "School of Liberal Arts",
        "School of Nursing",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 4,
        "School of Social & Behavioral Sciences": 1,
        "School of Business": 2,
        "School of Liberal Arts": 2,
        "School of Nursing": 1
      }
    },
    {
      "room": "MH280",
      "floor": "2",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 665,
      "seats": 32,
      "asfPerSeat": 20.8,
      "courseCount": 9,
      "seatOccupancy": 57,
      "weeklyHours": 24.9,
      "hoursPercent": 67,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 4,
        "School of Liberal Arts": 5
      }
    },
    {
      "room": "MH310",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 555,
      "seats": 29,
      "asfPerSeat": 19.1,
      "courseCount": 11,
      "seatOccupancy": 75,
      "weeklyHours": 28.9,
      "hoursPercent": 77,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences",
        "School of Health & Natural Sciences",
        "School of Business",
        "School of Education"
      ],
      "departmentUse": {
        "School of Business": 1,
        "School of Education": 1,
        "School of Liberal Arts": 4,
        "School of Health & Natural Sciences": 2,
        "School of Social & Behavioral Sciences": 3
      }
    },
    {
      "room": "MH312",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 558,
      "seats": 24,
      "asfPerSeat": 23.3,
      "courseCount": 11,
      "seatOccupancy": 79,
      "weeklyHours": 30.8,
      "hoursPercent": 83,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 10,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH316",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 375,
      "seats": 18,
      "asfPerSeat": 20.8,
      "courseCount": 7,
      "seatOccupancy": 80,
      "weeklyHours": 19.7,
      "hoursPercent": 53,
      "comment": "",
      "departments": [
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Liberal Arts": 7
      }
    },
    {
      "room": "MH324",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 562,
      "seats": 30,
      "asfPerSeat": 18.7,
      "courseCount": 9,
      "seatOccupancy": 77,
      "weeklyHours": 24.8,
      "hoursPercent": 66,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 3,
        "School of Liberal Arts": 3,
        "School of Social & Behavioral Sciences": 3
      }
    },
    {
      "room": "MH326",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 562,
      "seats": 30,
      "asfPerSeat": 18.7,
      "courseCount": 9,
      "seatOccupancy": 57,
      "weeklyHours": 21.4,
      "hoursPercent": 57,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 5,
        "School of Social & Behavioral Sciences": 2,
        "School of Liberal Arts": 2
      }
    },
    {
      "room": "MH332",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 410,
      "seats": 19,
      "asfPerSeat": 21.6,
      "courseCount": 5,
      "seatOccupancy": 72,
      "weeklyHours": 11.3,
      "hoursPercent": 30,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 2,
        "School of Social & Behavioral Sciences": 2,
        "School of Health & Natural Sciences": 1
      }
    },
    {
      "room": "MH364",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 980,
      "seats": 40,
      "asfPerSeat": 24.5,
      "courseCount": 12,
      "seatOccupancy": 68,
      "weeklyHours": 29.2,
      "hoursPercent": 78,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Nursing",
        "School of Liberal Arts",
        "School of Business"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 4,
        "School of Business": 1,
        "School of Liberal Arts": 3,
        "School of Nursing": 4
      }
    },
    {
      "room": "MH382",
      "floor": "3",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 656,
      "seats": 24,
      "asfPerSeat": 27.3,
      "courseCount": 11,
      "seatOccupancy": 78,
      "weeklyHours": 30.2,
      "hoursPercent": 81,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Health & Natural Sciences",
        "School of Business",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Business": 1,
        "School of Health & Natural Sciences": 4,
        "School of Liberal Arts": 5,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MHG2",
      "floor": "G",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 1261,
      "seats": 48,
      "asfPerSeat": 26.3,
      "courseCount": 12,
      "seatOccupancy": 57,
      "weeklyHours": 28.0,
      "hoursPercent": 75,
      "comment": "",
      "departments": [
        "School of Social & Behavioral Sciences",
        "School of Nursing",
        "School of Business",
        "School of Health & Natural Sciences",
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Business": 2,
        "School of Health & Natural Sciences": 2,
        "School of Liberal Arts": 1,
        "School of Social & Behavioral Sciences": 4,
        "School of Nursing": 3
      }
    },
    {
      "room": "MHG3",
      "floor": "G",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 1300,
      "seats": 48,
      "asfPerSeat": 27.1,
      "courseCount": 13,
      "seatOccupancy": 62,
      "weeklyHours": 28.2,
      "hoursPercent": 76,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences",
        "School of Business",
        "School of Nursing",
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Business": 3,
        "School of Liberal Arts": 2,
        "School of Social & Behavioral Sciences": 1,
        "School of Health & Natural Sciences": 4,
        "School of Nursing": 3
      }
    },
    {
      "room": "MHG4",
      "floor": "G",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "",
      "asf": 840,
      "seats": 28,
      "asfPerSeat": 30.0,
      "courseCount": 10,
      "seatOccupancy": 76,
      "weeklyHours": 29.5,
      "hoursPercent": 79,
      "comment": "",
      "departments": [
        "School of Social & Behavioral Sciences",
        "School of Nursing",
        "School of Health & Natural Sciences",
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Social & Behavioral Sciences": 5,
        "School of Liberal Arts": 1,
        "School of Health & Natural Sciences": 1,
        "School of Nursing": 3
      }
    },
    {
      "room": "MHLH",
      "floor": "",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "specialty": "Lecture hall",
      "asf": 2164,
      "seats": 178,
      "asfPerSeat": 12.2,
      "courseCount": 8,
      "seatOccupancy": 22,
      "weeklyHours": 19.3,
      "hoursPercent": 52,
      "comment": "",
      "departments": [
        "School of Nursing",
        "School of Health & Natural Sciences",
        "School of Liberal Arts"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 3,
        "School of Liberal Arts": 1,
        "School of Nursing": 4
      }
    },
    {
      "room": "MH217",
      "floor": "2",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Computer lab",
      "asf": 582,
      "seats": 20,
      "asfPerSeat": 29.1,
      "courseCount": 11,
      "seatOccupancy": 94,
      "weeklyHours": 31.5,
      "hoursPercent": 84,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 9,
        "School of Social & Behavioral Sciences": 2
      }
    },
    {
      "room": "MH239",
      "floor": "2",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Computer lab",
      "asf": 576,
      "seats": 18,
      "asfPerSeat": 32.0,
      "courseCount": 9,
      "seatOccupancy": 77,
      "weeklyHours": 21.4,
      "hoursPercent": 57,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 6,
        "School of Social & Behavioral Sciences": 3
      }
    },
    {
      "room": "MH277A",
      "floor": "2",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Nursing Basic Skills Lab",
      "asf": 1252,
      "seats": 24,
      "asfPerSeat": 52.2,
      "courseCount": 8,
      "seatOccupancy": 61,
      "weeklyHours": 20.0,
      "hoursPercent": 54,
      "comment": "",
      "departments": [
        "School of Nursing"
      ],
      "departmentUse": {
        "School of Nursing": 8
      }
    },
    {
      "room": "MH277B",
      "floor": "2",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Nursing Basic Skills Lab",
      "asf": 1430,
      "seats": 24,
      "asfPerSeat": 59.6,
      "courseCount": 5,
      "seatOccupancy": 57,
      "weeklyHours": 12.0,
      "hoursPercent": 32,
      "comment": "",
      "departments": [
        "School of Nursing"
      ],
      "departmentUse": {
        "School of Nursing": 5
      }
    },
    {
      "room": "MH279",
      "floor": "2",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Anatomy & Physiology Lab",
      "asf": 621,
      "seats": 20,
      "asfPerSeat": 31.1,
      "courseCount": 10,
      "seatOccupancy": 99,
      "weeklyHours": 28.3,
      "hoursPercent": 76,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 10
      }
    },
    {
      "room": "MH302",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Veterinary Technology Lab",
      "asf": 993,
      "seats": 24,
      "asfPerSeat": 41.4,
      "courseCount": 7,
      "seatOccupancy": 44,
      "weeklyHours": 23.8,
      "hoursPercent": 64,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 7
      }
    },
    {
      "room": "MH305",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "",
      "asf": 1222,
      "seats": 24,
      "asfPerSeat": 50.9,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "comment": "Evening and weekend only.",
      "departments": [],
      "departmentUse": {}
    },
    {
      "room": "MH309",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "General Chemistry Lab",
      "asf": 953,
      "seats": 20,
      "asfPerSeat": 47.7,
      "courseCount": 7,
      "seatOccupancy": 79,
      "weeklyHours": 19.8,
      "hoursPercent": 53,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 7
      }
    },
    {
      "room": "MH311",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Organic Chemistry Lab",
      "asf": 1236,
      "seats": 16,
      "asfPerSeat": 77.3,
      "courseCount": 5,
      "seatOccupancy": 88,
      "weeklyHours": 14.2,
      "hoursPercent": 38,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 5
      }
    },
    {
      "room": "MH313",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Computer lab",
      "asf": 513,
      "seats": 24,
      "asfPerSeat": 21.4,
      "courseCount": 8,
      "seatOccupancy": 64,
      "weeklyHours": 20.6,
      "hoursPercent": 55,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Liberal Arts": 7,
        "School of Social & Behavioral Sciences": 1
      }
    },
    {
      "room": "MH314",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Computer lab",
      "asf": 755,
      "seats": 20,
      "asfPerSeat": 37.8,
      "courseCount": 8,
      "seatOccupancy": 74,
      "weeklyHours": 20.5,
      "hoursPercent": 55,
      "comment": "",
      "departments": [
        "School of Liberal Arts",
        "School of Health & Natural Sciences",
        "School of Social & Behavioral Sciences"
      ],
      "departmentUse": {
        "School of Social & Behavioral Sciences": 1,
        "School of Liberal Arts": 6,
        "School of Health & Natural Sciences": 1
      }
    },
    {
      "room": "MH315",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Clinical Lab Science / Biology",
      "asf": 776,
      "seats": 18,
      "asfPerSeat": 43.1,
      "courseCount": 6,
      "seatOccupancy": 83,
      "weeklyHours": 26.2,
      "hoursPercent": 70,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 6
      }
    },
    {
      "room": "MH317",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Microbiology Lab",
      "asf": 742,
      "seats": 24,
      "asfPerSeat": 30.9,
      "courseCount": 7,
      "seatOccupancy": 78,
      "weeklyHours": 19.0,
      "hoursPercent": 51,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 6
      }
    },
    {
      "room": "MH318",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Physics Lab",
      "asf": 475,
      "seats": 16,
      "asfPerSeat": 29.7,
      "courseCount": 3,
      "seatOccupancy": 98,
      "weeklyHours": 17.0,
      "hoursPercent": 46,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 3
      }
    },
    {
      "room": "MH319",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "A&P / Vet Anatomy Lab",
      "asf": 772,
      "seats": 24,
      "asfPerSeat": 32.2,
      "courseCount": 5,
      "seatOccupancy": 63,
      "weeklyHours": 14.2,
      "hoursPercent": 38,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 5
      }
    },
    {
      "room": "MH321",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "General Biology Lab",
      "asf": 1045,
      "seats": 24,
      "asfPerSeat": 43.5,
      "courseCount": 7,
      "seatOccupancy": 79,
      "weeklyHours": 19.8,
      "hoursPercent": 53,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 7
      }
    },
    {
      "room": "MH322",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Biology Research Lab",
      "asf": 596,
      "seats": 8,
      "asfPerSeat": 74.5,
      "courseCount": 3,
      "seatOccupancy": 46,
      "weeklyHours": 17.0,
      "hoursPercent": 46,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 3
      }
    },
    {
      "room": "MH323",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Cell Biology Lab",
      "asf": 840,
      "seats": 20,
      "asfPerSeat": 42.0,
      "courseCount": 1,
      "seatOccupancy": 90,
      "weeklyHours": 5.7,
      "hoursPercent": 15,
      "comment": "",
      "departments": [
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 1
      }
    },
    {
      "room": "MH376",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Shared Skills Lab",
      "asf": 885,
      "seats": 24,
      "asfPerSeat": 36.9,
      "courseCount": 2,
      "seatOccupancy": 60,
      "weeklyHours": 4.0,
      "hoursPercent": 11,
      "comment": "",
      "departments": [
        "School of Nursing"
      ],
      "departmentUse": {
        "School of Nursing": 2
      }
    },
    {
      "room": "MH378",
      "floor": "3",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "specialty": "Shared Skills Lab",
      "asf": 970,
      "seats": 40,
      "asfPerSeat": 24.3,
      "courseCount": 4,
      "seatOccupancy": 39,
      "weeklyHours": 6.7,
      "hoursPercent": 18,
      "comment": "",
      "departments": [
        "School of Nursing",
        "School of Health & Natural Sciences"
      ],
      "departmentUse": {
        "School of Health & Natural Sciences": 1,
        "School of Nursing": 3
      }
    },
    {
      "room": "MH277C",
      "floor": "2",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "specialty": "Nursing SIM Lab",
      "asf": 189,
      "seats": 6,
      "asfPerSeat": 31.5,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "comment": "Open laboratory",
      "departments": [],
      "departmentUse": {}
    },
    {
      "room": "MH372",
      "floor": "3",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "specialty": "Health SIM / OT\u2013PT Lab",
      "asf": 529,
      "seats": 16,
      "asfPerSeat": 33.1,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "comment": "Open laboratory",
      "departments": [],
      "departmentUse": {}
    },
    {
      "room": "MH374",
      "floor": "3",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "specialty": "Movement Lab / OT\u2013PT",
      "asf": 1368,
      "seats": 40,
      "asfPerSeat": 34.2,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "comment": "Open laboratory",
      "departments": [],
      "departmentUse": {}
    }
  ]
};
