// Generated from Westchester tables in the April 2025 Rickes utilization report.
window.MERCY_WESTCHESTER = {
  "campus": "Westchester",
  "source": "Mercy University Instructional Space Needs Analysis, April 2025 (Rickes Associates)",
  "period": "Fall 2023 daytime instructional window (Mon\u2013Thu 8:00 AM\u20135:20 PM, 37.33 hrs/week)",
  "utilizationMetric": "Avg. percent of instructional-window hours scheduled (report \u201cAvg. Percent Hrs. Fall Day\u201d = weekly hours \u00f7 37.33)",
  "taxonomy": {
    "A": {
      "label": "A \u00b7 5\u201312 seats",
      "seats": "5\u201312",
      "color": "#F28620"
    },
    "B": {
      "label": "B \u00b7 13\u201318 seats",
      "seats": "13\u201318",
      "color": "#F9ED32"
    },
    "C": {
      "label": "C \u00b7 19\u201336 seats",
      "seats": "19\u201336",
      "color": "#49B0B9"
    },
    "D": {
      "label": "D \u00b7 37\u201374 seats",
      "seats": "37\u201374",
      "color": "#00AEEF"
    },
    "E": {
      "label": "E \u00b7 75\u2013200 seats",
      "seats": "75\u2013200",
      "color": "#3D54A5"
    },
    "F": {
      "label": "F \u00b7 201+ seats",
      "seats": "201+",
      "color": "#8B5E3C"
    }
  },
  "rooms": [
    {
      "room": "MEH030",
      "building": "Mercy Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 658,
      "seats": 30,
      "asfPerSeat": 21.9,
      "courseCount": 5,
      "seatOccupancy": 47,
      "weeklyHours": 14,
      "hoursPercent": 38,
      "utilization": 38,
      "comment": ""
    },
    {
      "room": "MEH031",
      "building": "Mercy Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 920,
      "seats": 48,
      "asfPerSeat": 19.2,
      "courseCount": 9,
      "seatOccupancy": 36,
      "weeklyHours": 25.3,
      "hoursPercent": 68,
      "utilization": 68,
      "comment": ""
    },
    {
      "room": "MEH032",
      "building": "Mercy Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 909,
      "seats": 48,
      "asfPerSeat": 18.9,
      "courseCount": 11,
      "seatOccupancy": 59,
      "weeklyHours": 30.3,
      "hoursPercent": 81,
      "utilization": 81,
      "comment": ""
    },
    {
      "room": "MH111",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 724,
      "seats": 36,
      "asfPerSeat": 20.1,
      "courseCount": 11,
      "seatOccupancy": 55,
      "weeklyHours": 29.7,
      "hoursPercent": 80,
      "utilization": 80,
      "comment": ""
    },
    {
      "room": "MH113",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1558,
      "seats": 36,
      "asfPerSeat": 43.3,
      "courseCount": 12,
      "seatOccupancy": 50,
      "weeklyHours": 32.8,
      "hoursPercent": 88,
      "utilization": 88,
      "comment": ""
    },
    {
      "room": "MH200",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 277,
      "seats": 15,
      "asfPerSeat": 18.5,
      "courseCount": 3,
      "seatOccupancy": 73,
      "weeklyHours": 7.1,
      "hoursPercent": 19,
      "utilization": 19,
      "comment": ""
    },
    {
      "room": "MH201",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 359,
      "seats": 20,
      "asfPerSeat": 18,
      "courseCount": 12,
      "seatOccupancy": 83,
      "weeklyHours": 32.4,
      "hoursPercent": 87,
      "utilization": 87,
      "comment": ""
    },
    {
      "room": "MH202",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 368,
      "seats": 24,
      "asfPerSeat": 15.3,
      "courseCount": 12,
      "seatOccupancy": 81,
      "weeklyHours": 36.2,
      "hoursPercent": 97,
      "utilization": 97,
      "comment": ""
    },
    {
      "room": "MH203",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 370,
      "seats": 20,
      "asfPerSeat": 18.5,
      "courseCount": 11,
      "seatOccupancy": 76,
      "weeklyHours": 29.4,
      "hoursPercent": 79,
      "utilization": 79,
      "comment": ""
    },
    {
      "room": "MH204",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 357,
      "seats": 20,
      "asfPerSeat": 17.9,
      "courseCount": 12,
      "seatOccupancy": 80,
      "weeklyHours": 33.3,
      "hoursPercent": 89,
      "utilization": 89,
      "comment": ""
    },
    {
      "room": "MH205",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 608,
      "seats": 30,
      "asfPerSeat": 20.3,
      "courseCount": 12,
      "seatOccupancy": 77,
      "weeklyHours": 31.3,
      "hoursPercent": 84,
      "utilization": 84,
      "comment": ""
    },
    {
      "room": "MH206",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 341,
      "seats": 18,
      "asfPerSeat": 18.9,
      "courseCount": 6,
      "seatOccupancy": 56,
      "weeklyHours": 13.8,
      "hoursPercent": 37,
      "utilization": 37,
      "comment": ""
    },
    {
      "room": "MH211",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 910,
      "seats": 42,
      "asfPerSeat": 21.7,
      "courseCount": 14,
      "seatOccupancy": 55,
      "weeklyHours": 35.8,
      "hoursPercent": 96,
      "utilization": 96,
      "comment": ""
    },
    {
      "room": "MH213",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 950,
      "seats": 30,
      "asfPerSeat": 31.7,
      "courseCount": 12,
      "seatOccupancy": 60,
      "weeklyHours": 32.7,
      "hoursPercent": 88,
      "utilization": 88,
      "comment": ""
    },
    {
      "room": "MH219",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 309,
      "seats": 18,
      "asfPerSeat": 17.2,
      "courseCount": 8,
      "seatOccupancy": 88,
      "weeklyHours": 22.7,
      "hoursPercent": 61,
      "utilization": 61,
      "comment": ""
    },
    {
      "room": "MH236",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 363,
      "seats": 18,
      "asfPerSeat": 20.2,
      "courseCount": 6,
      "seatOccupancy": 83,
      "weeklyHours": 17,
      "hoursPercent": 46,
      "utilization": 46,
      "comment": ""
    },
    {
      "room": "MH238",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 564,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 10,
      "seatOccupancy": 58,
      "weeklyHours": 30.2,
      "hoursPercent": 81,
      "utilization": 81,
      "comment": ""
    },
    {
      "room": "MH240",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 564,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 10,
      "seatOccupancy": 63,
      "weeklyHours": 29.3,
      "hoursPercent": 79,
      "utilization": 79,
      "comment": ""
    },
    {
      "room": "MH241",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 563,
      "seats": 30,
      "asfPerSeat": 18.8,
      "courseCount": 13,
      "seatOccupancy": 68,
      "weeklyHours": 35,
      "hoursPercent": 94,
      "utilization": 94,
      "comment": ""
    },
    {
      "room": "MH242",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 610,
      "seats": 35,
      "asfPerSeat": 17.4,
      "courseCount": 10,
      "seatOccupancy": 63,
      "weeklyHours": 24.7,
      "hoursPercent": 66,
      "utilization": 66,
      "comment": ""
    },
    {
      "room": "MH280",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 665,
      "seats": 32,
      "asfPerSeat": 20.8,
      "courseCount": 9,
      "seatOccupancy": 57,
      "weeklyHours": 24.9,
      "hoursPercent": 67,
      "utilization": 67,
      "comment": ""
    },
    {
      "room": "MH310",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 555,
      "seats": 29,
      "asfPerSeat": 19.1,
      "courseCount": 11,
      "seatOccupancy": 75,
      "weeklyHours": 28.9,
      "hoursPercent": 77,
      "utilization": 77,
      "comment": ""
    },
    {
      "room": "MH312",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 558,
      "seats": 24,
      "asfPerSeat": 23.3,
      "courseCount": 11,
      "seatOccupancy": 79,
      "weeklyHours": 30.8,
      "hoursPercent": 83,
      "utilization": 83,
      "comment": ""
    },
    {
      "room": "MH316",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 375,
      "seats": 18,
      "asfPerSeat": 20.8,
      "courseCount": 7,
      "seatOccupancy": 80,
      "weeklyHours": 19.7,
      "hoursPercent": 53,
      "utilization": 53,
      "comment": ""
    },
    {
      "room": "MH324",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 562,
      "seats": 30,
      "asfPerSeat": 18.7,
      "courseCount": 9,
      "seatOccupancy": 77,
      "weeklyHours": 24.8,
      "hoursPercent": 66,
      "utilization": 66,
      "comment": ""
    },
    {
      "room": "MH326",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 562,
      "seats": 30,
      "asfPerSeat": 18.7,
      "courseCount": 9,
      "seatOccupancy": 57,
      "weeklyHours": 21.4,
      "hoursPercent": 57,
      "utilization": 57,
      "comment": ""
    },
    {
      "room": "MH332",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 410,
      "seats": 19,
      "asfPerSeat": 21.6,
      "courseCount": 5,
      "seatOccupancy": 72,
      "weeklyHours": 11.3,
      "hoursPercent": 30,
      "utilization": 30,
      "comment": ""
    },
    {
      "room": "MH364",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 980,
      "seats": 40,
      "asfPerSeat": 24.5,
      "courseCount": 12,
      "seatOccupancy": 68,
      "weeklyHours": 29.2,
      "hoursPercent": 78,
      "utilization": 78,
      "comment": ""
    },
    {
      "room": "MH382",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 656,
      "seats": 24,
      "asfPerSeat": 27.3,
      "courseCount": 11,
      "seatOccupancy": 78,
      "weeklyHours": 30.2,
      "hoursPercent": 81,
      "utilization": 81,
      "comment": ""
    },
    {
      "room": "MHG2",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 1261,
      "seats": 48,
      "asfPerSeat": 26.3,
      "courseCount": 12,
      "seatOccupancy": 57,
      "weeklyHours": 28,
      "hoursPercent": 75,
      "utilization": 75,
      "comment": ""
    },
    {
      "room": "MHG3",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 1300,
      "seats": 48,
      "asfPerSeat": 27.1,
      "courseCount": 13,
      "seatOccupancy": 62,
      "weeklyHours": 28.2,
      "hoursPercent": 76,
      "utilization": 76,
      "comment": ""
    },
    {
      "room": "MHG4",
      "building": "Main Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 840,
      "seats": 28,
      "asfPerSeat": 30,
      "courseCount": 10,
      "seatOccupancy": 76,
      "weeklyHours": 29.5,
      "hoursPercent": 79,
      "utilization": 79,
      "comment": ""
    },
    {
      "room": "MHLH",
      "building": "Main Hall",
      "roomType": "Lecture Hall",
      "ficm": "FICM 610",
      "taxonomy": "E",
      "taxonomyLabel": "E \u00b7 75\u2013200 seats",
      "asf": 2164,
      "seats": 178,
      "asfPerSeat": 12.2,
      "courseCount": 8,
      "seatOccupancy": 22,
      "weeklyHours": 19.3,
      "hoursPercent": 52,
      "utilization": 52,
      "comment": ""
    },
    {
      "room": "VIC102",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "A",
      "taxonomyLabel": "A \u00b7 5\u201312 seats",
      "asf": 431,
      "seats": 12,
      "asfPerSeat": 35.9,
      "courseCount": 6,
      "seatOccupancy": 92,
      "weeklyHours": 17,
      "hoursPercent": 46,
      "utilization": 46,
      "comment": ""
    },
    {
      "room": "VIC103",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 572,
      "seats": 36,
      "asfPerSeat": 15.9,
      "courseCount": 11,
      "seatOccupancy": 56,
      "weeklyHours": 30.8,
      "hoursPercent": 83,
      "utilization": 83,
      "comment": ""
    },
    {
      "room": "VIC104",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 784,
      "seats": 35,
      "asfPerSeat": 22.4,
      "courseCount": 11,
      "seatOccupancy": 54,
      "weeklyHours": 28.4,
      "hoursPercent": 76,
      "utilization": 76,
      "comment": ""
    },
    {
      "room": "VIC105",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 773,
      "seats": 39,
      "asfPerSeat": 19.8,
      "courseCount": 8,
      "seatOccupancy": 59,
      "weeklyHours": 23.4,
      "hoursPercent": 63,
      "utilization": 63,
      "comment": ""
    },
    {
      "room": "VIC107",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 767,
      "seats": 40,
      "asfPerSeat": 19.2,
      "courseCount": 8,
      "seatOccupancy": 46,
      "weeklyHours": 22.5,
      "hoursPercent": 60,
      "utilization": 60,
      "comment": ""
    },
    {
      "room": "VIC108",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 759,
      "seats": 35,
      "asfPerSeat": 21.7,
      "courseCount": 7,
      "seatOccupancy": 42,
      "weeklyHours": 19.5,
      "hoursPercent": 52,
      "utilization": 52,
      "comment": ""
    },
    {
      "room": "VIC122",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 766,
      "seats": 16,
      "asfPerSeat": 47.9,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Unscheduled room."
    },
    {
      "room": "VIC206",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 1026,
      "seats": 40,
      "asfPerSeat": 25.7,
      "courseCount": 12,
      "seatOccupancy": 50,
      "weeklyHours": 32,
      "hoursPercent": 86,
      "utilization": 86,
      "comment": ""
    },
    {
      "room": "VIC216",
      "building": "Victory Hall",
      "roomType": "General-Purpose Classroom",
      "ficm": "FICM 100",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 332,
      "seats": 20,
      "asfPerSeat": 16.6,
      "courseCount": 9,
      "seatOccupancy": 87,
      "weeklyHours": 25,
      "hoursPercent": 67,
      "utilization": 67,
      "comment": ""
    },
    {
      "room": "GMH112",
      "building": "Gratia Mahony Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": null,
      "seats": 20,
      "asfPerSeat": null,
      "courseCount": 1,
      "seatOccupancy": 15,
      "weeklyHours": 2.8,
      "hoursPercent": 8,
      "utilization": 8,
      "comment": ""
    },
    {
      "room": "MEH029",
      "building": "Mercy Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 249,
      "seats": 32,
      "asfPerSeat": 7.8,
      "courseCount": 8,
      "seatOccupancy": 83,
      "weeklyHours": 24.8,
      "hoursPercent": 66,
      "utilization": 66,
      "comment": ""
    },
    {
      "room": "MH217",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 582,
      "seats": 20,
      "asfPerSeat": 29.1,
      "courseCount": 11,
      "seatOccupancy": 94,
      "weeklyHours": 31.5,
      "hoursPercent": 84,
      "utilization": 84,
      "comment": ""
    },
    {
      "room": "MH239",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 576,
      "seats": 18,
      "asfPerSeat": 32,
      "courseCount": 9,
      "seatOccupancy": 77,
      "weeklyHours": 21.4,
      "hoursPercent": 57,
      "utilization": 57,
      "comment": ""
    },
    {
      "room": "MH277A",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1252,
      "seats": 24,
      "asfPerSeat": 52.2,
      "courseCount": 8,
      "seatOccupancy": 61,
      "weeklyHours": 20,
      "hoursPercent": 54,
      "utilization": 54,
      "comment": ""
    },
    {
      "room": "MH277B",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1430,
      "seats": 24,
      "asfPerSeat": 59.6,
      "courseCount": 5,
      "seatOccupancy": 57,
      "weeklyHours": 12,
      "hoursPercent": 32,
      "utilization": 32,
      "comment": ""
    },
    {
      "room": "MH279",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 621,
      "seats": 20,
      "asfPerSeat": 31.1,
      "courseCount": 10,
      "seatOccupancy": 99,
      "weeklyHours": 28.3,
      "hoursPercent": 76,
      "utilization": 76,
      "comment": ""
    },
    {
      "room": "MH302",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 993,
      "seats": 24,
      "asfPerSeat": 41.4,
      "courseCount": 7,
      "seatOccupancy": 44,
      "weeklyHours": 23.8,
      "hoursPercent": 64,
      "utilization": 64,
      "comment": ""
    },
    {
      "room": "MH305",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1222,
      "seats": 24,
      "asfPerSeat": 50.9,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Evening and weekend only."
    },
    {
      "room": "MH309",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 953,
      "seats": 20,
      "asfPerSeat": 47.7,
      "courseCount": 7,
      "seatOccupancy": 79,
      "weeklyHours": 19.8,
      "hoursPercent": 53,
      "utilization": 53,
      "comment": ""
    },
    {
      "room": "MH311",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 1236,
      "seats": 16,
      "asfPerSeat": 77.3,
      "courseCount": 5,
      "seatOccupancy": 88,
      "weeklyHours": 14.2,
      "hoursPercent": 38,
      "utilization": 38,
      "comment": ""
    },
    {
      "room": "MH313",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 513,
      "seats": 24,
      "asfPerSeat": 21.4,
      "courseCount": 8,
      "seatOccupancy": 64,
      "weeklyHours": 20.6,
      "hoursPercent": 55,
      "utilization": 55,
      "comment": ""
    },
    {
      "room": "MH314",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 755,
      "seats": 20,
      "asfPerSeat": 37.8,
      "courseCount": 8,
      "seatOccupancy": 74,
      "weeklyHours": 20.5,
      "hoursPercent": 55,
      "utilization": 55,
      "comment": ""
    },
    {
      "room": "MH315",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 776,
      "seats": 18,
      "asfPerSeat": 43.1,
      "courseCount": 6,
      "seatOccupancy": 83,
      "weeklyHours": 26.2,
      "hoursPercent": 70,
      "utilization": 70,
      "comment": ""
    },
    {
      "room": "MH317",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 742,
      "seats": 24,
      "asfPerSeat": 30.9,
      "courseCount": 7,
      "seatOccupancy": 78,
      "weeklyHours": 19,
      "hoursPercent": 51,
      "utilization": 51,
      "comment": ""
    },
    {
      "room": "MH318",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 475,
      "seats": 16,
      "asfPerSeat": 29.7,
      "courseCount": 3,
      "seatOccupancy": 98,
      "weeklyHours": 17,
      "hoursPercent": 46,
      "utilization": 46,
      "comment": ""
    },
    {
      "room": "MH319",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 772,
      "seats": 24,
      "asfPerSeat": 32.2,
      "courseCount": 5,
      "seatOccupancy": 63,
      "weeklyHours": 14.2,
      "hoursPercent": 38,
      "utilization": 38,
      "comment": ""
    },
    {
      "room": "MH321",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1045,
      "seats": 24,
      "asfPerSeat": 43.5,
      "courseCount": 7,
      "seatOccupancy": 79,
      "weeklyHours": 19.8,
      "hoursPercent": 53,
      "utilization": 53,
      "comment": ""
    },
    {
      "room": "MH322",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "A",
      "taxonomyLabel": "A \u00b7 5\u201312 seats",
      "asf": 596,
      "seats": 8,
      "asfPerSeat": 74.5,
      "courseCount": 3,
      "seatOccupancy": 46,
      "weeklyHours": 17,
      "hoursPercent": 46,
      "utilization": 46,
      "comment": ""
    },
    {
      "room": "MH323",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 840,
      "seats": 20,
      "asfPerSeat": 42,
      "courseCount": 1,
      "seatOccupancy": 90,
      "weeklyHours": 5.7,
      "hoursPercent": 15,
      "utilization": 15,
      "comment": ""
    },
    {
      "room": "MH376",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 885,
      "seats": 24,
      "asfPerSeat": 36.9,
      "courseCount": 2,
      "seatOccupancy": 60,
      "weeklyHours": 4,
      "hoursPercent": 11,
      "utilization": 11,
      "comment": ""
    },
    {
      "room": "MH378",
      "building": "Main Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 970,
      "seats": 40,
      "asfPerSeat": 24.3,
      "courseCount": 4,
      "seatOccupancy": 39,
      "weeklyHours": 6.7,
      "hoursPercent": 18,
      "utilization": 18,
      "comment": ""
    },
    {
      "room": "VIC101",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 1045,
      "seats": 23,
      "asfPerSeat": 45.4,
      "courseCount": 4,
      "seatOccupancy": 79,
      "weeklyHours": 11.3,
      "hoursPercent": 30,
      "utilization": 30,
      "comment": ""
    },
    {
      "room": "VIC110",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 775,
      "seats": 32,
      "asfPerSeat": 24.2,
      "courseCount": 10,
      "seatOccupancy": 61,
      "weeklyHours": 28.3,
      "hoursPercent": 76,
      "utilization": 76,
      "comment": ""
    },
    {
      "room": "VIC114",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 0,
      "seats": 40,
      "asfPerSeat": 0,
      "courseCount": 10,
      "seatOccupancy": 45,
      "weeklyHours": 28.2,
      "hoursPercent": 76,
      "utilization": 76,
      "comment": ""
    },
    {
      "room": "VIC115",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 1040,
      "seats": 16,
      "asfPerSeat": 65,
      "courseCount": 2,
      "seatOccupancy": 53,
      "weeklyHours": 5.7,
      "hoursPercent": 15,
      "utilization": 15,
      "comment": ""
    },
    {
      "room": "VIC120",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 766,
      "seats": 30,
      "asfPerSeat": 25.5,
      "courseCount": 3,
      "seatOccupancy": 28,
      "weeklyHours": 9,
      "hoursPercent": 24,
      "utilization": 24,
      "comment": ""
    },
    {
      "room": "VIC123",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 766,
      "seats": 16,
      "asfPerSeat": 47.9,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Spring only."
    },
    {
      "room": "VIC200",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 441,
      "seats": 16,
      "asfPerSeat": 27.6,
      "courseCount": 7,
      "seatOccupancy": 63,
      "weeklyHours": 19.8,
      "hoursPercent": 53,
      "utilization": 53,
      "comment": ""
    },
    {
      "room": "VIC203",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 556,
      "seats": 18,
      "asfPerSeat": 30.9,
      "courseCount": 8,
      "seatOccupancy": 78,
      "weeklyHours": 24.7,
      "hoursPercent": 66,
      "utilization": 66,
      "comment": ""
    },
    {
      "room": "VIC204",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 549,
      "seats": 18,
      "asfPerSeat": 30.5,
      "courseCount": 8,
      "seatOccupancy": 62,
      "weeklyHours": 24.2,
      "hoursPercent": 65,
      "utilization": 65,
      "comment": ""
    },
    {
      "room": "VIC207",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 358,
      "seats": 15,
      "asfPerSeat": 23.9,
      "courseCount": 4,
      "seatOccupancy": 65,
      "weeklyHours": 11.3,
      "hoursPercent": 30,
      "utilization": 30,
      "comment": ""
    },
    {
      "room": "VIC208",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 803,
      "seats": 16,
      "asfPerSeat": 50.2,
      "courseCount": 10,
      "seatOccupancy": 76,
      "weeklyHours": 44.2,
      "hoursPercent": 118,
      "utilization": 118,
      "comment": ""
    },
    {
      "room": "VIC210",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "A",
      "taxonomyLabel": "A \u00b7 5\u201312 seats",
      "asf": 766,
      "seats": 12,
      "asfPerSeat": 63.8,
      "courseCount": 5,
      "seatOccupancy": 112,
      "weeklyHours": 22.1,
      "hoursPercent": 59,
      "utilization": 59,
      "comment": ""
    },
    {
      "room": "VIC212",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 786,
      "seats": 32,
      "asfPerSeat": 24.6,
      "courseCount": 10,
      "seatOccupancy": 88,
      "weeklyHours": 29.5,
      "hoursPercent": 79,
      "utilization": 79,
      "comment": ""
    },
    {
      "room": "VIC214",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 756,
      "seats": 32,
      "asfPerSeat": 23.6,
      "courseCount": 12,
      "seatOccupancy": 85,
      "weeklyHours": 33.3,
      "hoursPercent": 89,
      "utilization": 89,
      "comment": ""
    },
    {
      "room": "VIC215",
      "building": "Victory Hall",
      "roomType": "Teaching Laboratory",
      "ficm": "FICM 210",
      "taxonomy": "C",
      "taxonomyLabel": "C \u00b7 19\u201336 seats",
      "asf": 855,
      "seats": 30,
      "asfPerSeat": 28.5,
      "courseCount": 6,
      "seatOccupancy": 62,
      "weeklyHours": 16.8,
      "hoursPercent": 45,
      "utilization": 45,
      "comment": ""
    },
    {
      "room": "MH277C",
      "building": "Main Hall",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "taxonomy": "A",
      "taxonomyLabel": "A \u00b7 5\u201312 seats",
      "asf": 189,
      "seats": 6,
      "asfPerSeat": 31.5,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Open laboratory"
    },
    {
      "room": "MH372",
      "building": "Main Hall",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "taxonomy": "B",
      "taxonomyLabel": "B \u00b7 13\u201318 seats",
      "asf": 529,
      "seats": 16,
      "asfPerSeat": 33.1,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Open laboratory"
    },
    {
      "room": "MH374",
      "building": "Main Hall",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "taxonomy": "D",
      "taxonomyLabel": "D \u00b7 37\u201374 seats",
      "asf": 1368,
      "seats": 40,
      "asfPerSeat": 34.2,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Open laboratory"
    },
    {
      "room": "VIC205B",
      "building": "Victory Hall",
      "roomType": "Open Laboratory",
      "ficm": "FICM 220",
      "taxonomy": "A",
      "taxonomyLabel": "A \u00b7 5\u201312 seats",
      "asf": 745,
      "seats": 10,
      "asfPerSeat": 74.5,
      "courseCount": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "hoursPercent": null,
      "utilization": null,
      "comment": "Open laboratory"
    }
  ],
  "byBuilding": {
    "Main Hall": {
      "rooms": 53,
      "scheduled": 49,
      "utilization": 62.5,
      "seatOccupancy": 69.4,
      "weeklyHours": 23.3,
      "courses": 417,
      "seats": 1494,
      "asf": 40003,
      "weeklyHoursTotal": 1141.3
    },
    "Mercy Hall": {
      "rooms": 4,
      "scheduled": 4,
      "utilization": 63.2,
      "seatOccupancy": 56.2,
      "weeklyHours": 23.6,
      "courses": 33,
      "seats": 158,
      "asf": 2736,
      "weeklyHoursTotal": 94.4
    },
    "Victory Hall": {
      "rooms": 25,
      "scheduled": 22,
      "utilization": 61.7,
      "seatOccupancy": 65.6,
      "weeklyHours": 23.0,
      "courses": 171,
      "seats": 629,
      "asf": 17217,
      "weeklyHoursTotal": 507.0
    },
    "Gratia Mahony Hall": {
      "rooms": 1,
      "scheduled": 1,
      "utilization": 8.0,
      "seatOccupancy": 15.0,
      "weeklyHours": 2.8,
      "courses": 1,
      "seats": 20,
      "asf": 0,
      "weeklyHoursTotal": 2.8
    }
  },
  "byTaxonomy": {
    "A": {
      "label": "A \u00b7 5\u201312 seats",
      "seats": 48,
      "color": "#F28620",
      "rooms": 5,
      "scheduled": 3,
      "utilization": 50.3,
      "seatOccupancy": 83.3,
      "weeklyHours": 18.7,
      "courses": 14,
      "weeklyHoursTotal": 56.1,
      "asf": 2727
    },
    "B": {
      "label": "B \u00b7 13\u201318 seats",
      "seats": 302,
      "color": "#F9ED32",
      "rooms": 18,
      "scheduled": 15,
      "utilization": 51.6,
      "seatOccupancy": 74.9,
      "weeklyHours": 19.3,
      "courses": 92,
      "weeklyHoursTotal": 289.0,
      "asf": 10536
    },
    "C": {
      "label": "C \u00b7 19\u201336 seats",
      "seats": 1260,
      "color": "#49B0B9",
      "rooms": 47,
      "scheduled": 46,
      "utilization": 63.6,
      "seatOccupancy": 67.7,
      "weeklyHours": 23.7,
      "courses": 395,
      "weeklyHoursTotal": 1091.5,
      "asf": 33345
    },
    "D": {
      "label": "D \u00b7 37\u201374 seats",
      "seats": 513,
      "color": "#00AEEF",
      "rooms": 12,
      "scheduled": 11,
      "utilization": 70.6,
      "seatOccupancy": 52.4,
      "weeklyHours": 26.3,
      "courses": 113,
      "weeklyHoursTotal": 289.6,
      "asf": 11184
    },
    "E": {
      "label": "E \u00b7 75\u2013200 seats",
      "seats": 178,
      "color": "#3D54A5",
      "rooms": 1,
      "scheduled": 1,
      "utilization": 52.0,
      "seatOccupancy": 22.0,
      "weeklyHours": 19.3,
      "courses": 8,
      "weeklyHoursTotal": 19.3,
      "asf": 2164
    },
    "F": {
      "label": "F \u00b7 201+ seats",
      "seats": 0,
      "color": "#8B5E3C",
      "rooms": 0,
      "scheduled": 0,
      "utilization": null,
      "seatOccupancy": null,
      "weeklyHours": null,
      "courses": 0,
      "weeklyHoursTotal": 0,
      "asf": 0
    }
  },
  "byBuildingTaxonomy": {
    "Main Hall": {
      "A": 46.0,
      "B": 47.4,
      "C": 66.5,
      "D": 68.6,
      "E": 52.0,
      "F": null
    },
    "Mercy Hall": {
      "A": null,
      "B": null,
      "C": 52.0,
      "D": 74.5,
      "E": null,
      "F": null
    },
    "Victory Hall": {
      "A": 52.5,
      "B": 57.8,
      "C": 62.1,
      "D": 71.2,
      "E": null,
      "F": null
    },
    "Gratia Mahony Hall": {
      "A": null,
      "B": null,
      "C": 8.0,
      "D": null,
      "E": null,
      "F": null
    }
  },
  "byManagement": {
    "General-purpose / registrar classrooms": {
      "rooms": 42,
      "utilization": 69.9,
      "courses": 398,
      "weeklyHoursTotal": 1067.8
    },
    "Specialty teaching & open labs": {
      "rooms": 41,
      "utilization": 51.9,
      "courses": 224,
      "weeklyHoursTotal": 677.7
    }
  },
  "byManagementTaxonomy": {
    "General-purpose / registrar classrooms": {
      "A": 46.0,
      "B": 43.2,
      "C": 74.7,
      "D": 75.9,
      "E": 52.0,
      "F": null
    },
    "Specialty teaching & open labs": {
      "A": 52.5,
      "B": 55.8,
      "C": 50.4,
      "D": 47.0,
      "E": null,
      "F": null
    }
  },
  "dayOfWeek": {
    "label": "Peak simultaneous classrooms in use \u2014 Fall 2023 (not a sample week)",
    "activeClassrooms": 41,
    "peakSimultaneous": 38,
    "note": "No sample-week or multi-week reservation feed is in the source files. These figures are Fall 2023 peak simultaneous classroom counts by weekday from the Westchester utilization chart (Rickes report). Thursday reached the campus maximum of 38 of 41 active classrooms.",
    "days": [
      {
        "day": "Monday",
        "peakRooms": 37,
        "utilization": 90.2
      },
      {
        "day": "Tuesday",
        "peakRooms": 35,
        "utilization": 85.4,
        "note": "SHNS peak 11 classrooms"
      },
      {
        "day": "Wednesday",
        "peakRooms": 37,
        "utilization": 90.2
      },
      {
        "day": "Thursday",
        "peakRooms": 38,
        "utilization": 92.7,
        "note": "Campus max; Nursing peak 6"
      },
      {
        "day": "Friday",
        "peakRooms": 20,
        "utilization": 48.8
      },
      {
        "day": "Saturday",
        "peakRooms": 7,
        "utilization": 17.1
      },
      {
        "day": "Sunday",
        "peakRooms": 5,
        "utilization": 12.2
      }
    ]
  },
  "timeOfDay": {
    "available": true,
    "note": "Campus-wide simultaneous-classroom curves (Fall 2023) are digitised from the report's vector artwork on p.42 and rendered in westchester_time_of_day.js."
  },
  "totals": {
    "rooms": 83,
    "scheduled": 76,
    "asf": 59956,
    "seats": 2301,
    "courses": 622,
    "utilization": 61.6,
    "weeklyHoursTotal": 1745.5
  }
};
